parameters:
#    cabinet_user.example.class: Cabinet\UserBundle\Example

services:
#    cabinet_user.example:
#        class: %cabinet_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
